# ----------------------------------------------------------------------------------------------------------------------
#
#   Virtual environment
#
# ----------------------------------------------------------------------------------------------------------------------
# Documentation
#   * Official
#     * https://docs.gitlab.com/ee/ci/yaml/
#     * https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
#
#   * Japanese
#     * https://gitlab-docs.creationline.com/ee/ci/yaml/README.html
#
# ----------------------------------------------------------------------------------------------------------------------
#
#   Template Jobs
#
# ----------------------------------------------------------------------------------------------------------------------
.pip:
  before_script:
    - apt-get update > /dev/null
    - apt-get install -y --no-install-recommends python3-pip > /dev/null

.requirements-packages:
  before_script:
    - apt-get update > /dev/null
    - apt-get install -y --no-install-recommends python3-pip > /dev/null
    - pip3 install -r "${REQUIREMENTS_TXT_PATH}"